// Package handler_api Generated by the api tool.  DO NOT EDIT!
package handler_api

import (
	"github.com/lfxnxf/emo-frame/zd_http/http_ctx"
	"github.com/lfxnxf/emo-frame/zd_http/server"
	"io"
	"net/http"
	"os"
	"strconv"
)

func initRoute(g *server.HttpGroup) {

	g.GET("/test_download", func(c *http_ctx.HttpContext) {
		w := c.Writer
		file, _ := os.Open("/work/test.pdf")
		defer file.Close()

		fileHeader := make([]byte, 512)
		file.Read(fileHeader)

		fileStat, _ := file.Stat()

		w.Header().Set("Content-Disposition", "attachment; filename=test.pdf")
		w.Header().Set("Content-Type", http.DetectContentType(fileHeader))
		w.Header().Set("Content-Length", strconv.FormatInt(fileStat.Size(), 10))

		file.Seek(0, 0)
		io.Copy(w, file)

		return
	})

}
