apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  labels:
    name: ${namespace}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-gateway
  name: api-gateway
  namespace: ${namespace}
spec:
  replicas: ${replica_num}
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-gateway
    spec:
      containers:
      - image: ${tag}
        name: api-gateway
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        resources: {}
        volumeMounts:
        - name: logs
          mountPath: /logs
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: logs
          hostPath:
            path: /work/logs/api-gateway-${namespace}
            type: DirectoryOrCreate
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: ${namespace}
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10000
      nodePort: ${node_port}
  type: NodePort
